using UnityEngine;

/// <summary>
/// Stores all configuration for a single puzzle level.
/// 
/// This is a ScriptableObject — a data container asset that lives in your
/// Project folder. You create instances via:
///   Right-click in Project → Create → 4Blocks → Level Data
///
/// WHY ScriptableObject?
///   - Levels are pure data (positions, sizes) — no runtime logic needed
///   - Easy to create/edit in Inspector without touching code
///   - Reusable: LevelManager reads this to spawn walls + blocks
///   - Swappable: just drag a different LevelData asset to load a new level
///
/// WHAT'S STORED:
///   - Grid dimensions (width × height)
///   - 4 block start positions (where blocks spawn)
///   - 4 block target positions (where blocks need to end up for a win)
///   - Interior wall positions (walls inside the arena; boundary walls are
///     auto-generated by LevelManager based on grid size)
/// </summary>
[CreateAssetMenu(fileName = "NewLevel", menuName = "4Blocks/Level Data")]
public class LevelData : ScriptableObject
{
    [Header("Level Info")]
    [Tooltip("Display name shown in the HUD")]
    public string levelName = "Level 01";

    [Tooltip("If true, each block MUST reach its specific target (Block 1 to Target 1, etc.). If false, any block can reach any target.")]
    public bool requireExactTargetMatch = false;

    [Header("Grid Dimensions")]
    [Tooltip("Width of the play area in grid cells")]
    public int gridWidth = 5;

    [Tooltip("Height of the play area in grid cells")]
    public int gridHeight = 5;

    [Header("Block Positions (4 blocks)")]
    [Tooltip("Starting grid positions for each of the 4 blocks")]
    public Vector2Int[] blockStartPositions = new Vector2Int[4];

    [Tooltip("Target grid positions — all 4 blocks must reach these to win")]
    public Vector2Int[] blockTargetPositions = new Vector2Int[4];

    [Header("Interior Walls")]
    [Tooltip("Grid positions of walls INSIDE the arena (boundary walls are auto-generated)")]
    public Vector2Int[] wallPositions;
}
